### ISSUE TITLE
Base German Localization

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/gow-stuff-i18n#6]
- [x] common.json
- [x] platforms.json
- [x] languages.json
- [x] game.json
- [x] pages.json
- [x] home.json
- [x] events.json
- [x] guild.json
- [x] guildwars.json
- [x] pvp.json
- [x] tasks.json
- [x] error.json
- [x] changelog.md
- [x] privacy.md

**Comment by EliteMasterEric** [comment]
Events: Resolved by #1 
Game: Resolved by #3 
Guild: Resolved by #4 
Languages: Resolved #5

**Comment by maduck** [comment]
all added in #18

**Comment by EliteMasterEric** [comment]
Great work!

Next steps are to:

* Ideally localize changelog.md (not super necessary)
* Look for and resolve any differences with @Lluna13's changes.

**Comment by maduck** [comment]
changelog was empty by the time. i will update accordingly.

**Comment by maduck** [comment]
done. feedback also incorporated.

**Comment by maduck** [comment]
Consistency check with Lluna13's translation done. Ready to go @MasterEric :)

**Comment by EliteMasterEric** [comment]
Resolved by #18 .
